/*
**
** File: cf_external_functions.h
** This file is automatically generated by the
** chain flow assembler
** Build Time: 2018-10-03 17:05:58.409456  
**
*/

#ifndef _EXTERNAL_FUNCTIONS_H_
#define _EXTERNAL_FUNCTIONS_H_ 

#include "chain_flow_support.h" 
#include "cf_events.h"
/*
This is the symbolic definitions of the chains
*/



#define  initialization   0
#define  feed_watch_dog   1
#define  pulse_task   2



/*
This is the symbolic definitions of the links for chain initialization
*/
#define  initialization_0   0
#define  initialization_1   1
#define  initialization_2   2
#define  initialization_3   3
#define  initialization_4   4
#define  initialization_5   5
#define  initialization_6   6
#define  initialization_7   7



/*
This is the symbolic definitions of the links for chain feed_watch_dog
*/
#define  feed_watch_dog_0   0
#define  feed_watch_dog_1   1
#define  feed_watch_dog_2   2



/*
This is the symbolic definitions of the links for chain pulse_task
*/
#define  pulse_task_0   0
#define  pulse_task_1   1
#define  pulse_task_2   2
#define  pulse_task_3   3
#define  pulse_task_4   4



int analog_ouptut_subscribe_output(CHAIN_FLOW_HANDLE *cf, unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int analog_output_subscribe_configuration(CHAIN_FLOW_HANDLE *cf, unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int analog_output_subscribe_pulse_output(CHAIN_FLOW_HANDLE *cf, unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int pat_watch_dog(CHAIN_FLOW_HANDLE *cf, unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int wait_for_mqtt_connect(CHAIN_FLOW_HANDLE *cf, unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int add_watch_dog(CHAIN_FLOW_HANDLE *cf, unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int analog_output_store_cf_handle_ref(CHAIN_FLOW_HANDLE *cf, unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int analog_output_step_timer(CHAIN_FLOW_HANDLE *cf, unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int analog_output_set_final_value(CHAIN_FLOW_HANDLE *cf, unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int analog_output_set_initial_value(CHAIN_FLOW_HANDLE *cf, unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);






#endif
